Update index html file
st-lanphan/FE-Internship-Summer-2022_st-lanphan_FE-Exercise pull request #2
Opened 2022-06-08 09:17 UTC by st-lanphan

2022-06-08 09:38 UTC, st-vantran commented on index.html
> +            <img src="" alt="">
Logo thêm link <a> vào nhé e. Alt thêm nội dung vào.

2022-06-08 09:39 UTC, st-lanphan commented on index.html
> +            <img src="" alt="">
oke anh

2022-06-08 10:09 UTC, st-vantran commented on index.html
> +                    <p>T-Shirt Summer Vibes</p>
Thẻ h3

2022-06-08 10:09 UTC, st-vantran commented on index.html
> +            <ul>
Text `Why should you choose us` đâu rồi?

2022-06-08 10:09 UTC, st-vantran commented on index.html
> +            <div class="contact-btn">
Thêm thẻ form khi dùng input

2022-06-08 10:09 UTC, st-vantran commented on index.html
> +                <img src="#" alt="img">
Logo thêm thẻ a

2022-06-08 12:01 UTC, st-lanphan commented on index.html
> +                    <img src="" alt="img">
này em chưa hiểu lắm anh.Anh giải thích giúp em với

2022-06-08 15:11 UTC, st-vantran commented on index.html
> +                    <img src="" alt="img">
Là thêm 1 class giành cho phần giảm giá á em

2022-06-08 15:30 UTC, st-vantran commented on index.html
>      <header>
header, footer, main thêm class vào nhé e

2022-06-08 15:30 UTC, st-vantran commented on index.html
> +      <section class="banner">
nên đặt tên là section-banner nhé e

2022-06-08 15:30 UTC, st-vantran commented on index.html
> +              <p>Free Shipping</p>
Title thì dùng thẻ H

2022-06-08 15:30 UTC, st-vantran commented on index.html
> +      <section class="new">
tên class="new" không nên đặt. Tên đây nên đặt section-collection

2022-06-08 15:33 UTC, st-lanphan commented on index.html
>      <header>
em nghĩ những cái đó chỉ có 1 block duy nhất nên cũng không đặt tên

2022-06-08 15:59 UTC, st-vantran commented on index.html
> +      <section class="selected">
section for-you

2022-06-08 15:59 UTC, st-vantran commented on index.html
> +        <ul class="selected-list">
tên class ul thường là nouns-list (products-list)
li thường là noun-item (product-item)
a thường là noun-link (product-link)

2022-06-08 15:59 UTC, st-vantran commented on index.html
> +            <div class="product-item">
product thường là link nên thay bằng thẻ a nhé e

2022-06-08 15:59 UTC, st-vantran commented on index.html
> +        <ul class="about-us-list">
đặt tên class ul li như cmt  trên nhé e

2022-06-08 15:59 UTC, st-vantran commented on index.html
> +        <ul class="selected-list">
đặt tên class ul li

2022-06-08 15:59 UTC, st-vantran commented on index.html
> +            <div class="product-item">
thẻ a

2022-06-08 15:59 UTC, st-vantran commented on index.html
> +          <ul class="social-list">
tên class ul li

2022-06-08 15:59 UTC, st-vantran commented on index.html
> +                <li>store@uikit.com</li>
với những link email hoặc số điện thoại nên dùng thẻ <a href= "mailto:abc@example.com"><a href="tel:xxx-xxx-xxx">

2022-06-08 15:59 UTC, st-vantran commented on index.html
> +    <p>DESIGN BY ICEO.CO - © 2019. ALL RIGHTS RESERVED.</p>
thẻ p này không class thì sao css được

2022-06-08 16:41 UTC, st-vantran commented on index.html
> +                <h6>store@uikit.com</h6>
sao h6 ở đây? thẻ <a tel hoặc mailto mà

2022-06-08 16:43 UTC, st-vantran commented on index.html
> +            </div>
mở thẻ a mà đóng thẻ div

2022-06-08 16:43 UTC, st-vantran commented on index.html
> +        <ul class="product-list">
products có s

2022-06-08 16:44 UTC, st-vantran commented on index.html
> +      <section class="section-for-you">
section-foryou nhé e

2022-06-08 16:48 UTC, st-vantran commented on index.html
> +        <ul class="nav">
đặt tên class lại nghen, nav là gì ?

2022-06-08 17:24 UTC, st-vantran commented on index.html
> +              <h5>99% Satisfied Customers</h5>
sao lại có h5 ở đây

2022-06-08 17:24 UTC, st-vantran commented on README.md
> +##### I am a 3rd year student at Danang University of Education
File này không cần. Checkout ra nhé e

2022-06-08 22:41 UTC, st-lanphan commented on index.html
> +              <h5>99% Satisfied Customers</h5>
em nghĩ ở đây là sub title nên sử dụng h5

2022-06-09 09:52 UTC, st-vantran reviewed
Xem lại format prettier nhé em, các tag cách nhau không đều

2022-06-09 09:52 UTC, st-vantran commented on index.html
> +                  <div>
Thường ở đây mình sẽ dùng row ở `<ul>` và dùng col ở `<li>` nhé e

2022-06-09 09:52 UTC, st-vantran commented on index.html
> +            <input type="text" name="femail" id="rmail" value="Enter your email">
name="femail" + id="rmail"?
value = "Enter your email" ? cái text này là ở placeholder mà e

2022-06-09 15:25 UTC, st-trangnguyen requested changes

2022-06-09 15:25 UTC, st-trangnguyen commented on index.html
> +          <h2 class="headline">Sale of the <span>summer</span> colletion</h2>
```<h2 class="headline">Sale of the <span>summer</span> colletion</h2>
          <a href="#"><i class="fas fa-arrow-alt-circle-right"></i> Shoping now</a>```
Em nên bọc lại 1 div banner-content

2022-06-09 15:25 UTC, st-trangnguyen commented on index.html
> +            <div class="collection row">
em đưa row lên ul, và col vào li, xóa các div dư đi nhé

2022-06-09 15:25 UTC, st-trangnguyen commented on index.html
> +                      <li class="class=collection-item">
???

2022-06-09 15:25 UTC, st-trangnguyen commented on index.html
> +          <div class="product-content">
section-heading

2022-06-09 15:25 UTC, st-trangnguyen commented on index.html
> +              <div class="products col-3">
tương tự em đưa row vào ul và col vào li

2022-06-09 15:25 UTC, st-trangnguyen commented on index.html
> +          <div class="today-content">
ko cần div này

2022-06-09 15:25 UTC, st-trangnguyen commented on index.html
> +              <ul>
ul rùi a a ?? u là trời

2022-06-10 08:18 UTC, merged