code sass fashion page
st-lanphan/FE-Internship-Summer-2022_st-lanphan_FE-Exercise pull request #6
Opened 2022-06-15 01:38 UTC by st-lanphan

2022-06-15 08:39 UTC, st-trangnguyen requested changes
- Em sửa lại tên file css nhé. style-demo là gì hè
- check lại convention, indent space, empty line ở cuối file

2022-06-15 09:38 UTC, st-trangnguyen requested changes
- file name kể cả image em đặt theo convention là `snake-case`
- trong block sass em đưa các mixin lên đầu tiên

2022-06-15 09:38 UTC, st-trangnguyen commented on stylesheet/base/_grid.scss
> +@use "sass:math";
file grid là thuộc về layout

2022-06-15 09:38 UTC, st-trangnguyen commented on stylesheet/base/_all.scss
> +@import "./base";
import chưa đúng thứ tự

reset
font
variable
mixin
extend
base

lý do: ví dụ variable đc import sau base thì ở file base mình sẽ ko dùng được những biến define ở variable

2022-06-15 09:38 UTC, st-trangnguyen commented on stylesheet/base/_reset.scss
> +body {
cái này là base của trang web

2022-06-15 09:38 UTC, st-trangnguyen commented on stylesheet/base/_mixins.scss
> +@mixin setFont(
tên của mixin đặt theo kiểu snake-case

2022-06-15 09:38 UTC, st-trangnguyen commented on stylesheet/layout/_header.scss
> +    @include align-center;
sao ko dùng flex-center luôn em

2022-06-15 09:38 UTC, st-trangnguyen commented on stylesheet/layout/_header.scss
> +      height: 800%;
height 800%?

2022-06-15 09:38 UTC, st-trangnguyen commented on stylesheet/modules/discount.scss
> +.card-discount {
module này là `badge`. chị nhớ chị đã chỉ chỗ này rồi `https://getbootstrap.com/docs/4.0/components/badge/`

2022-06-16 02:11 UTC, st-lanphan commented on stylesheet/layout/_header.scss
> +    @include align-center;
em dùng flex-center với align-center cũng không có thay đổi gì nên em lấy align-center luôn á chị

2022-06-16 02:12 UTC, st-lanphan commented on stylesheet/layout/_header.scss
> +      height: 800%;
done

2022-06-16 02:37 UTC, st-lanphan commented on stylesheet/base/_all.scss
> +@import "./base";
done

2022-06-16 02:39 UTC, st-lanphan commented on stylesheet/base/_reset.scss
> +body {
done

2022-06-16 02:43 UTC, st-lanphan commented on stylesheet/base/_mixins.scss
> +@mixin setFont(
done

2022-06-16 12:39 UTC, st-lanphan commented on stylesheet/base/_grid.scss
> +@use "sass:math";
done

2022-06-16 12:51 UTC, st-lanphan commented on stylesheet/modules/discount.scss
> +.card-discount {
done

2022-06-17 13:36 UTC, st-trangnguyen reviewed
Chị merge cái này vào để em làm bài tập giỏ hàng nhé. Có thời gian xem phần sass để cải thiện nhé

2022-06-17 13:38 UTC, merged